name: Full Backend Build, Format, and Test

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

  pull_request:
    paths:
      - "backend/**"
    branches:
      - main

defaults:
  run:
    working-directory: backend

env:
  dotnet-version: 6.0.x

jobs:
  build:
    name: Full build validation
    runs-on: ubuntu-latest

    # concurrency:
    #   group: ${{ github.ref }}-build-backend
    #   cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - run: dotnet restore

      - run: dotnet build --no-restore

      - run: dotnet test --no-build --verbosity normal
  crlf-check:
    name: Check CRLF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v1

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1.2.0
        with:
          path: ./backend
