name: Full Frontend Build, Format, and Test

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main

  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main

defaults:
  run:
    working-directory: frontend

env:
  node-version: 14.x

jobs:
  build:
    name: Full build validation
    runs-on: ubuntu-latest

    # concurrency:
    #   group: ${{ github.ref }}-build-frontend
    #   cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ env.node-version }}

      - run: npm ci

      - run: npm run build

      - run: npm run test:headless

  crlf-check:
    name: Check CRLF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v1

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1.2.0
        with:
          path: ./frontend
